export class Postacourse {
    maincategory: string;
    subcategory1: string; 
    subcategory2: string; 
    subcategory3: string;
    subcategory4: string; 
    subcategory5: string;
    academiclevels:string;
    courseTypeId:string;
    courseCode:string;
    
    universityTypeId:string;
    universityName:string;
    availableSeats:string;
    accademicYear:string;
    accademicYearMonth:string;
    courseDuration:string;
    examConducted:string;
    courseSyllabusFile:string;
    admissionStartDate:string;
    admissionCloseDate:string;
    classStartDate:string;
    maleAllowed:string;
    femaleAllowed:string;
    otherGenderAllowed:string;
    campusAddressLine1:string;
    campusAddressLine2:string;
    campusAddressLine3:string;
    country:string;
    block:string;
    locality:string;
    refundPolicy:string;
    onlineClassAvailability:string;
    aptituteTestRequired:string;
    aptituteTestId:string;
    onlineInterviewRequired:string;
    eligibiliyInString:string;
    jobAreas:string;
    jobPositions:string;
    salaryRange:string;
    hasPlacementAssistant:string;
    recruiters:string;
    isActive:string;
    accademicLevelCourseId:string;
    instituteId:string;
    courseStreamId:string;
    courseStreamSpecializationId:string;
    CourseCategoryId:string;
    CourseSubCategoryId:string;
    CourseSubCategory2Id:string;
    CourseSubCategory3Id:string;
    CourseSubCategory4Id:string;
    CourseSubCategory5Id:string;
    campusName:string;
    feepaymenttenure:string;
    bankAcoount:string;
    courseFee:string;
    Scholarship:string;
    ValidUpto:string;
    ScholarshipAmount:string;
}